#!/bin/bash

### TODO on each build: update mrenclave in session

docker-compose down > /dev/null
docker network create scone-net > /dev/null
echo "Starting CAS & LAS:"
docker-compose up -d
sleep 5

MY_SCONE_APP=nexus.iex.ec/tee-worker-pre-compute:d21eb78-dev-local
echo "Starting $MY_SCONE_APP"
docker run --rm \
        --name=my-scone-app \
        -e SCONE_VERSION=1 \
        -e SCONE_CAS_ADDR="cas" \
        -e SCONE_LAS_ADDR="las" \
        -e SCONE_CONFIG_ID="sessionId/pre-compute" \
        -v /tmp/iexec_in:/iexec_in \
        --network=scone-net \
        --device=/dev/isgx \
        $MY_SCONE_APP

docker-compose down
docker network rm scone-net
