/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.iexec.worker.tee.pre;

import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    void should() {
    }
    
}
