/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.iexec.worker.tee.pre;

import com.iexec.common.precompute.PreComputeUtils;
import com.iexec.common.utils.IexecEnvUtils;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.MockitoAnnotations;
import org.mockito.Spy;

import java.io.File;

import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.when;

class PreComputeAppTests {

    private static final String DIR = "src/test/resources/";
    private static final String ENC_DATA_FILE = DIR + "encrypted-data.bin";
    private static final String PLAIN_DATA_FILE = DIR + "key.txt";
    private static final String KEY_FILE = DIR + "plain-data.txt";

    private static final String TASK_ID = "taskId";
    private static final String IEXEC_IN =  "taskId";
    private static final String TASK_ID = "taskId";
    private static final String TASK_ID = "taskId";

    @TempDir
    private File tempDir;

    @Spy
    private PreComputeApp preComputeApp;

    @BeforeEach
    void beforeEach() throws Exception {
        MockitoAnnotations.openMocks(this);
        when(preComputeApp.getEnvVarOrThrow(IexecEnvUtils.IEXEC_TASK_ID_ENV_PROPERTY)).thenReturn("string");
        when(preComputeApp.getEnvVarOrThrow(IexecEnvUtils.IEXEC_IN_ENV_PROPERTY)).thenReturn("string");
        when(preComputeApp.getEnvVarOrThrow(PreComputeUtils.IEXEC_DATASET_KEY_PROPERTY)).thenReturn("string");
        when(preComputeApp.getEnvVarOrThrow(PreComputeUtils.IEXEC_DATASET_CHECKSUM_PROPERTY)).thenReturn("string");
        when(preComputeApp.getEnvVarOrThrow(IexecEnvUtils.IEXEC_DATASET_FILENAME_ENV_PROPERTY)).thenReturn("string");
    }


    @Test
    void shouldStart() throws Exception {
        when(preComputeApp.getEnvVarOrThrow(anyString())).thenReturn("env");
        System.out.println(System.getenv(IexecEnvUtils.IEXEC_TASK_ID_ENV_PROPERTY));
    }
    
}
